# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

language: php

php:
    - 7.1
    - 7.2

sudo: false

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
    - phpunit